### ISSUE TITLE
Use port 80 or 443 for notebook and bokeh application?

### ISSUE THREAD

**Issue by mrocklin** [martindurant/dask-kubernetes#14]
By convention we serve on ports 8787 (dask/bokeh) and 8888 (jupyter).  However these ports may be blocked within enterprise environments.  Perhaps we should serve on typical ports like 80 (for http) and 443 (for https) which are usually not blocked?

**Comment by mrocklin** [comment]
Thoughts on this @martindurant ?

**Comment by martindurant** [comment]
Fixed in #25
