### ISSUE TITLE
Include Bokeh server for one worker

### ISSUE THREAD

**Issue by mrocklin** [martindurant/dask-kubernetes#18]
So my understanding is that it is difficult to provide an external view of the bokeh server page for each worker.  However, is it possible to provide an external view of the bokeh server page for one worker?  It can be very helpful to get information from a representative worker.

**Comment by martindurant** [comment]
Yes, we could certainly expose one random worker. Subsequent reloads of the page would presumably go to another worker; but I imagine bokeh's websocket is stable.
