### ISSUE TITLE
Command to print out useful information

### ISSUE THREAD

**Issue by mrocklin** [martindurant/dask-kubernetes#19]
After creating the cluster I need to know a few things like where the jupyter notebook and bokeh page are.  The README is quite good about pointing me to `kubectl get services -l app=dask`.  Relying on kubernetes in this way may be the right approach to avoid endless scope.  However, if we do want to start doing more things like resize it would be convenient to have the important addresses printed out on the console so that I could easily copy-paste and put into my web browser (or click on them, if my terminal highlights appropriately turns them into links). 

Additionally, it would be useful to get instructions on how to launch the kubernetes web interface.  I think that this is typically done by setting up some sort of proxy.  Launching the web interface might be sufficient to cover a lot of the requests like resize.  We could just say "oh, just launch the web interface and it should be easy to do from there."

**Comment by jbcrail** [comment]
I have a similar proposal in #11 based on `dask-ec2 dask-distributed address`.
