### ISSUE TITLE
GCSFS fails to initialize

### ISSUE THREAD

**Issue by mrocklin** [martindurant/dask-kubernetes#20]
```python
>>> fs = gcsfs.GCSFileSystem()
Enter the following code when prompted in the browser:
XXXX-XXXX
RuntimeError: Waited too long for browserauthentication.
```

If we are running from gcloud there *must* be some way of using the existing credentials.  We might be able to ask our Google contacts about this.

**Comment by martindurant** [comment]
At the very least, there should be good documentation around this. The thing to do is log in with the google cloud CLI and point GCS to the generated token.

**Comment by mrocklin** [comment]
From https://cloud.google.com/storage/docs/authentication

If you're running your application on Google App Engine or Google Compute Engine, the environment already provides a [service account's](https://developers.google.com/identity/protocols/OAuth2ServiceAccount) authentication information, so no further setup is required. For Compute Engine, the service account scope depends on how you created the instance. See [Setting the scope of service account access for instances](https://cloud.google.com/compute/docs/access/create-enable-service-accounts-for-instances#using). For App Engine, the cloud-platform scope is used.

I'm not sure if this is helpful or not, but seems possibly related.

**Comment by mrocklin** [comment]
> At the very least, there should be good documentation around this. The thing to do is log in with the google cloud CLI and point GCS to the generated token.

Docs would be appreciated.  Grabbing S3 data from GCE is proving unpredictable at the moment.

**Comment by martindurant** [comment]
Got something working, fix in dask-kuberneter and gcsfs coming soon.

**Comment by martindurant** [comment]
See also https://github.com/martindurant/dask-kubernetes/commit/5ec053eb96fc2cbbed7e7860dd6223657c9654c9
