### ISSUE TITLE
Unable to connect to scheduler

### ISSUE THREAD

**Issue by mrocklin** [martindurant/dask-kubernetes#22]
I gave the recent changes a shot.  First time through I was able to connect to the scheduler but the workers kept going up and down.  Second time through I'm unable to connect to the scheduler.

**Comment by martindurant** [comment]
I am not seeing this, I wonder what is going on.
I notice that the bokeh application screen loads for scheduler or worker, but none of the screens display - could this be the tornado/bokeh incompatibility? That might have killed the scheduler or workers in your case.

**Comment by martindurant** [comment]
Also, if I connect from a local python, I see "unknown opcode" when submitting a function - can that be because I have py35 here but the workers are py36?

**Comment by mrocklin** [comment]
Tornado does appear to be 4.5.  If you only conda install things then you
should be safe.  Alternatively we could pin to 4.4

**Comment by martindurant** [comment]
Forced tornado 4.4 in https://github.com/martindurant/dask-kubernetes/commit/020d7b6a77d284d600a3f5f751e46907e6386d5f - dashboards are working again. Does this solve the dead processes?

**Comment by mrocklin** [comment]
Things *do* seem to be working for me.  I am somewhat surprised about this though.  I was definitely seeing workers die and come back.  I'm not sure how the bokeh+tornado conflict would cause this.

**Comment by mrocklin** [comment]
This is happening again.  Workers are coming and going constantly.

```python
list(client.scheduler_info()['workers'])
['tcp://127.0.0.1:36429',
 'tcp://127.0.0.1:43951',
 'tcp://127.0.0.1:43452',
 'tcp://127.0.0.1:40105',
 'tcp://127.0.0.1:46845',
 'tcp://127.0.0.1:33897',
 'tcp://127.0.0.1:41170',
 'tcp://127.0.0.1:39442']

>>> list(client.scheduler_info()['workers'])
['tcp://127.0.0.1:43452',
 'tcp://127.0.0.1:40105',
 'tcp://127.0.0.1:46845',
 'tcp://127.0.0.1:33897',
 'tcp://127.0.0.1:41170',
 'tcp://127.0.0.1:39442']
```

**Comment by martindurant** [comment]
Would you please check on the kube dashboard or with kubectl get pods whether it is the containers that are restarting?

**Comment by martindurant** [comment]
OK, seen it myself for the first time. 
The pods are all alive and happy, and workers alive on another node/IP persist nicely, but ALL workers on 127.0.0.1 repeatedly birth and die. I don't understand how any pod can be talking to its (internal) loopback.

**Comment by mrocklin** [comment]
One option here would be to specify the network interface explicitly when starting dask-workers with the `--interface` keyword

    dask-worker dask-scheduler:8786 --interface eth0

This would stop workers from connecting to loopback (though I agree with you that it's odd to see them do this).  You would have to check the proper name of the wired network using `ifconfig`

http://stackoverflow.com/questions/43881157/how-do-i-use-an-infiniband-network-with-dask

**Comment by martindurant** [comment]
OK, so my suspicion is that this arises because of providing the Service to workers to allow the bokeh dashboard of one of them to be seen, which is a new feature. It takes a while for services to come up, and I guess the network config changes when it does. 
So I could poll the code currently in info() waiting for the service to be live and only assign workers afterwards. That would also allow to print the relevant addresses so that the user can get going. That would mean always starting with 0 workers and scaling up - easier achieved if the kube prescriptions are already parameterized.

**Comment by mrocklin** [comment]
I would also be fine losing the worker dashboard if that is causing
issues.  It's a nice-to-have, but not critical.

**Comment by martindurant** [comment]
Would you like to try #23?
I have both removed the worker service and included the interface parameter too - seems to run OK for me (tried a couple of times).
The wait-until-ready can be done later.
