### ISSUE TITLE
Deleting a cluster should delete associated resources

### ISSUE THREAD

**Issue by koverholt** [martindurant/dask-kubernetes#32]
I believe that the command `dask-kubernetes delete NAME` only deletes the GKE cluster, but does not delete the associated [load balancer(s)](https://github.com/martindurant/dask-kubernetes/blob/b2cb0c8aaa97afd4ca1c529b65b87dd337b52784/dask_kubernetes/kubernetes/dask_external.yaml#L8-L15) from GCP, which continue to run in terms of compute and billing.

`dask-kubernetes delete NAME` should delete the GKE cluster and associated resources on GCP.

**Comment by martindurant** [comment]
Any idea how this is done? Do you have evidence that such extra billing is happening?

**Comment by koverholt** [comment]
Yes, we had ~100 load balancers in our GCP account that were created (but not deleted) by dask-kubernetes, and the instances that were associated with those load balancers no longer existed.

The second highest charge in our GCP account was `Network Load Balancing: Forwarding Rule Additional Service Charge in Americas`, which was related to those unused load balancers.

**Comment by martindurant** [comment]
OK, so I'll fold it in - but do you happen to know how to delete them?

**Comment by koverholt** [comment]
I believe it's done via the `gcloud compute forwarding-rules delete` command.

**Comment by martindurant** [comment]
Fixed in https://github.com/martindurant/dask-kubernetes/commit/0f32dcd7e994313048ceddcdd78b234176d6fa59
(was **not** easy to find the information, and I don't like the amount of querying it takes - might be fragile to the future - and having to confirm thrice. I don't suppose I can use `yes` because of windows?)
