### ISSUE TITLE
Add JupyterLab service

### ISSUE THREAD

**Issue by mrocklin** [martindurant/dask-kubernetes#33]
It would be interesting (and community-minded) to add a JupyterLab instance running alongside the class Jupyter notebook.

**Comment by martindurant** [comment]
You mean both live, but listening on different ports?

**Comment by mrocklin** [comment]
Perhaps?  What are your thoughts on this?

**Comment by martindurant** [comment]
Certainly doable with not much effort.

**Comment by martindurant** [comment]
Fixed in https://github.com/martindurant/dask-kubernetes/pull/35
