### ISSUE TITLE
Increase scheduler memory

### ISSUE THREAD

**Issue by mrocklin** [martindurant/dask-kubernetes#39]
For large graphs we can easily extend beyond the 1GB limit here.  We might consider going to 2GB or 4GB.

**Comment by martindurant** [comment]
Does the client need to have increased memory too, then? The current default is 2GB.

Out of interest, do you know how many tasks in a graph it typically takes to fill 1GB of scheduler memory, and how much of this is sent down the wire (as opposed to copied between internal structures)?

**Comment by mrocklin** [comment]
Here they are combined:

```python
In [1]: import psutil

In [2]: psutil.Process().memory_info()
Out[2]: pmem(rss=38862848, vms=287846400, shared=9134080, text=4096, lib=0, data=182284288, dirty=0)

In [3]: _.rss / 1e6
Out[3]: 38.862848

In [4]: from dask.distributed import Client, wait

In [5]: psutil.Process().memory_info()
Out[5]: pmem(rss=64720896, vms=420515840, shared=16982016, text=4096, lib=0, data=199528448, dirty=0)

In [6]: _.rss / 1e6
Out[6]: 64.720896

In [7]: client = Client()

In [8]: psutil.Process().memory_info().rss / 1e6
Out[8]: 111.075328

In [9]: def inc(x):
   ...:     return x + 1
   ...: 

In [10]: futures = client.map(inc, range(100009)); wait(futures);

In [11]: psutil.Process().memory_info().rss / 1e6
Out[11]: 850.223104
```

100k tasks requires around a GB.  This would grow larger for more complex tasks.

Additionally sometimes people often put data like numpy arrays into task graphs.  Additionally they might want to do non-trivial local work in their notebook.  Maybe 4-8 GB would be safer?

**Comment by martindurant** [comment]
Fixed in https://github.com/martindurant/dask-kubernetes/commit/1f073420a028d15d72ce722a1535336d6eff4fdb
