### ISSUE TITLE
CLI for cluster management

### ISSUE THREAD

**Issue by jbcrail** [martindurant/dask-kubernetes#7]
This will replace `scripts/make_cluster.sh` and is loosely based on the command `gcloud dataproc clusters` but specific to Dask.

Example usage:
```
$ dask-kube
Usage: dask-kube [--version] [--help] <command> [args]

Create and manage Dask clusters using Kubernetes on Google Cloud Platform.

Common commands:
    create             Create a cluster.
    delete             Delete a cluster.
    update             Update cluster configuration.
    describe           Show the details of a cluster.
    list               Show all clusters.
```

**Comment by martindurant** [comment]
I'm sure you are already on it, but if would be nice to provide various parameters here, either as command line, environment variables (maybe) or a single conf file. The kubernetes templates could be written in [helm syntax](https://github.com/kubernetes/helm/blob/master/docs/charts.md#template-files) with appropriate [parameter files](https://github.com/kubernetes/helm/blob/master/docs/charts.md#values-files) to make this more portable.

**Comment by martindurant** [comment]
PS: why dask-kube and not dask-kubernetes for the command? Everyone has tab-completion, so no need to spare keystrokes.

**Comment by mrocklin** [comment]
+1 on the idea.  +1 on dask-kubernetes

Thoughts on adding a `scale` command to scale up or down?

Is there a way in which this can also be useful when using an institutional Kubernetes deployment rather than Google cloud?

**Comment by martindurant** [comment]
Yes, when we talked, we thought there could be a two-stage setup: to separate gcloud cluster create and kubernetes actions. In the manner of the old acluster, it should be possible to define the cluster by hand (or inherit kubernetes environment variables) and act on it.

**Comment by jbcrail** [comment]
@martindurant @mrocklin I confess I have a preference for pithy names. I agree the full name is clearer, more descriptive, and a better choice.

The `update` subcommand would allow adjusting the cluster settings (e.g. number of worker nodes). The subcommand was borrowed from `gcloud` for familiarity, but `scale` could be used also.

**Comment by jbcrail** [comment]
@martindurant I intend to add command-line parameter support in the first implementation. I'm not familiar with `helm` syntax as I'm still learning the Kubernetes ecosystem, but it looks to be a good fit for our use cases.

**Comment by martindurant** [comment]
"number of worker nodes" - for the enterprise situation, you probably can't do this; what you *can* do is change the number of worker-containers that run on the predefined cluster.

**Comment by mrocklin** [comment]
From a user perspective one of the most common operations I expect to do is to change the number of dask workers in my cluster.  I expect that with `update` the best way to do this is to go into a json file and modify a number somewhere.  We can all do this obviously, but I suspect that the average user will find it frustrating.  I agree that this would probably happen after other things happen.

**Comment by martindurant** [comment]
There is a kubernetes rescale command, no need to modify anything; although it would be good to keep track locally of changes we've made to the cluster, even if you can always fetch the information using kubectl.
